Repository dbeaver/dbeaver, pull requests merged in 2020-04, with the labels that each got.

#8312 #8301 Fix regression bug for reserved words
  plugins/org.jkiss.dbeaver.ext.exasol/src/org/jkiss/dbeaver/ext/exasol/ExasolSQLDialect.java
Labels: bug

#8315 #8314 Fix visibility of Security tree for version 7.0
  plugins/org.jkiss.dbeaver.ext.exasol/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.ext.exasol/OSGI-INF/l10n/bundle_de.properties
  plugins/org.jkiss.dbeaver.ext.exasol/OSGI-INF/l10n/bundle_ja.properties
  plugins/org.jkiss.dbeaver.ext.exasol/OSGI-INF/l10n/bundle_ru.properties
  plugins/org.jkiss.dbeaver.ext.exasol/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ext.exasol/plugin.xml
  plugins/org.jkiss.dbeaver.ext.exasol/src/org/jkiss/dbeaver/ext/exasol/model/ExasolCurrentUserPrivileges.java
  plugins/org.jkiss.dbeaver.ext.exasol/src/org/jkiss/dbeaver/ext/exasol/model/ExasolDataSource.java
Labels: bug, x:exasol

#8343 OpenTopoMap leaflet - GIS data view
  plugins/org.jkiss.dbeaver.data.gis.view/plugin.xml
Labels: enhancement

#8387 GIS data viewer : popular TileLayers (v2)
  plugins/org.jkiss.dbeaver.data.gis.view/plugin.xml
Labels: feature request

#8547 fix CASE ... WHEN ... END indent
  plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/format/tokenized/IndentFormatter.java
Labels: bug
