Repository dbeaver/dbeaver, pull requests merged in 2020-09, with the labels that each got.

#9234 Issue 4729: adding a new action that save a temp file of a blob and p…
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/data/managers/ContentValueManager.java
Labels: feature request

#9817 Elasticsearch JDBC driver repo and version update
  plugins/org.jkiss.dbeaver.ext.elasticsearch/plugin.xml
Labels: enhancement

#9884 MySQL 8: fix duplicates in foreign keys
  plugins/org.jkiss.dbeaver.ext.mysql/src/org/jkiss/dbeaver/ext/mysql/model/MySQLTable.java
  plugins/org.jkiss.dbeaver.ext.mysql/src/org/jkiss/dbeaver/ext/mysql/model/MySQLTableForeignKey.java
Labels: bug, x:mysql
