Repository dbeaver/dbeaver, pull requests merged in 2021-01, with the labels that each got.

#10851 l10n: Update Spanish translation, part 1
  plugins/org.jkiss.dbeaver.core/OSGI-INF/l10n/bundle_es.properties
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources_es.properties
  plugins/org.jkiss.dbeaver.tasks.ui/OSGI-INF/l10n/bundle_es.properties
  plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/internal/CoreApplicationMessages_es.properties
  plugins/org.jkiss.dbeaver.ui.dashboard/src/org/jkiss/dbeaver/ui/dashboard/internal/UIDashboardMessages_es.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/OSGI-INF/l10n/bundle_es.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/OSGI-INF/l10n/bundle_es.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages_es.properties
  plugins/org.jkiss.dbeaver.ui.navigator/OSGI-INF/l10n/bundle_es.properties
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/internal/UINavigatorMessages_es.properties
  plugins/org.jkiss.dbeaver.ui.search/OSGI-INF/l10n/bundle_es.properties
Labels: enhancement, xf:i18n

#10868 hana connection dialog: preset instance number from port when migrating from generic edition to platform edition
  plugins/org.jkiss.dbeaver.ext.hana.ui/src/org/jkiss/dbeaver/ext/hana/ui/views/HANAConnectionPage.java
Labels: enhancement, x:hana

#10925 Add Trino driver configuration
  plugins/org.jkiss.dbeaver.ext.generic/icons/trino_icon.png
  plugins/org.jkiss.dbeaver.ext.generic/icons/trino_icon@2x.png
  plugins/org.jkiss.dbeaver.ext.generic/icons/trino_icon_big.png
  plugins/org.jkiss.dbeaver.ext.generic/icons/trino_icon_big@2x.png
  plugins/org.jkiss.dbeaver.ext.generic/plugin.xml
Labels: feature request

#11079 use recent version of mariadb-connector-j
  plugins/org.jkiss.dbeaver.ext.mysql/plugin.xml
Labels: enhancement, x:maria
