Repository dbeaver/dbeaver, pull requests merged in 2022-12, with the labels that each got.

#18408 Fix french translation
  plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/internal/DTUIMessages_fr.properties
Labels: external

#18436 Fix translation
  plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/internal/ERDUIMessages_de.properties
Labels: external

#18467 dbeaver/pro#1238 Respect mouse position when zooming charts in/out
  plugins/org.jkiss.dbeaver.ui.charts/src/org/jkiss/dbeaver/ui/charts/BaseChartComposite.java
Labels: build:ee

#18431 #6830 SQLite extension management
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/actions/DataSourcePropertyTester.java
  plugins/org.jkiss.dbeaver.ext.generic.ui/src/org/jkiss/dbeaver/ext/generic/views/GenericConnectionPage.java
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/DBPDataSourceProviderSynchronizable.java
  plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/DataSourceDescriptor.java
  plugins/org.jkiss.dbeaver.ui.editors.connection/src/org/jkiss/dbeaver/ui/dialogs/connection/ConnectionPageWithAuth.java
Labels: build:ee

#18311 #17162 Complete some Simplified Chinese localization work
  plugins/org.jkiss.dbeaver.cmp.simple.ui/src/org/jkiss/dbeaver/tools/compare/simple/ui/internal/CompareUIMessages_zh.properties
  plugins/org.jkiss.dbeaver.core/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources_zh.properties
  plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/internal/DTUIMessages_zh.properties
  plugins/org.jkiss.dbeaver.data.transfer/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/internal/DTMessages_zh.properties
  plugins/org.jkiss.dbeaver.ext.mysql.ui/src/org/jkiss/dbeaver/ext/mysql/ui/internal/MySQLUIMessages_zh.properties
  plugins/org.jkiss.dbeaver.ext.mysql/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ext.mysql/plugin.xml
  plugins/org.jkiss.dbeaver.ext.oracle.ui/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ext.oracle/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/internal/OracleMessages_zh.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.model/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/messages/ModelResources_zh.properties
  plugins/org.jkiss.dbeaver.registry/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/internal/RegistryMessages_zh.properties
  plugins/org.jkiss.dbeaver.tasks.native.ui/src/org/jkiss/dbeaver/tasks/ui/nativetool/internal/TaskNativeUIMessages_zh.properties
  plugins/org.jkiss.dbeaver.tasks.ui.view/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.tasks.ui/src/org/jkiss/dbeaver/tasks/ui/internal/TaskUIMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.base/src/org/jkiss/dbeaver/ui/editors/internal/EditorsResources_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.connection/src/org/jkiss/dbeaver/ui/internal/UIConnectionMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/internal/ResultSetMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/editors/data/internal/DataEditorsResources_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.hex/src/org/jkiss/dbeaver/ui/editors/binary/internal/BinaryEditorMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql.terminal/src/org/jkiss/dbeaver/ui/editors/sql/terminal/SQLTerminalMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.navigator/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/internal/UINavigatorMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/internal/UIMessages_zh.properties
Labels: sp:1, external

#18228 #17554-Fix-for-MySQL-username-with-proper-back-quotes
  plugins/org.jkiss.dbeaver.ext.mysql/src/org/jkiss/dbeaver/ext/mysql/model/MySQLUser.java
Labels: external

#18510 #18090 Update Athena driver version to 2.0.34
  plugins/org.jkiss.dbeaver.ext.athena/plugin.xml
Labels: build:ee

#18548 dbeaver/pro#1252 move to EE SSO and change password features
  plugins/org.jkiss.dbeaver.ext.snowflake.core/plugin.xml
  plugins/org.jkiss.dbeaver.ext.snowflake.core/src/org/jkiss/dbeaver/ext/snowflake/model/SnowflakeChangeUserPasswordManager.java
  plugins/org.jkiss.dbeaver.ext.snowflake.core/src/org/jkiss/dbeaver/ext/snowflake/model/SnowflakeDataSource.java
  plugins/org.jkiss.dbeaver.ext.snowflake.core/src/org/jkiss/dbeaver/ext/snowflake/model/auth/SnowflakeAuthModelExternalBrowser.java
  plugins/org.jkiss.dbeaver.ext.snowflake.ui/plugin.xml
  plugins/org.jkiss.dbeaver.ext.snowflake.ui/src/org/jkiss/dbeaver/ext/snowflake/ui/config/SnowflakeAuthExternalBrowserConfigurator.java
Labels: build:ee

#18600 dbeaver/pro#1332 Fix value handler for EE extension
  plugins/org.jkiss.dbeaver.ext.sqlite/plugin.xml
Labels: build:ee

#18561 dbeaver/pro#440 Filters restore fix
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/DataFilterRegistry.java
Labels: build:ee
