Repository dbeaver/dbeaver, pull requests merged in 2022-09, with the labels that each got.

#17592 dbeaver/dbeaver-ee#1266 refactor connection URL for connection config…
  plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/PostgreDataSourceProvider.java
  plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/driver/DriverDescriptor.java
Labels: build:ee

#17632 dbeaver/dbeaver#17621 update sequence DDL after object refresh
  plugins/org.jkiss.dbeaver.ext.vertica/src/org/jkiss/dbeaver/ext/vertica/model/VerticaSequence.java
Labels: build:ee

#17446 Update zh translation.
  plugins/org.jkiss.dbeaver.core/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources_zh.properties
  plugins/org.jkiss.dbeaver.ext.generic.ui/src/org/jkiss/dbeaver/ext/generic/internal/GenericResources_zh.properties
  plugins/org.jkiss.dbeaver.ext.mysql/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.model/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/messages/ModelResources_zh.properties
  plugins/org.jkiss.dbeaver.ui.app.eclipse/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.navigator/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/internal/UIMessages_zh.properties
Labels: sp:1

#17642 dbeaver/dbeaver-ee#1694 stop Spanner driver on the working driver ver…
  plugins/org.jkiss.dbeaver.ext.spanner/plugin.xml
Labels: build:ue

#17650 dbeaver/dbeaver-ee#1909 Project and resource persmissions support
  plugins/org.jkiss.dbeaver.core/plugin.xml
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/actions/DataSourcePropertyTester.java
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/actions/common/AddBookmarkHandler.java
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/actions/datasource/DataSourceReadonlyHandler.java
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/actions/datasource/ToolsContextMenuHandler.java
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/resources/bookmarks/DBNBookmark.java
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/resources/bookmarks/DBNBookmarkFolder.java
  plugins/org.jkiss.dbeaver.erd.ui/plugin.xml
  plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/editor/ERDEditorStandalone.java
  plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/navigator/DBNDiagram.java
  plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/navigator/DBNDiagramFolder.java
  plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/navigator/DiagramCreateWizard.java
  plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/navigator/DiagramCreateWizardPage.java
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/DBIconComposite.java
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNResource.java
  plugins/org.jkiss.dbeaver.ui.app.eclipse/plugin.xml
  plugins/org.jkiss.dbeaver.ui.app.standalone/plugin.xml
  plugins/org.jkiss.dbeaver.ui.editors.base/src/org/jkiss/dbeaver/ui/editors/EditorUtils.java
  plugins/org.jkiss.dbeaver.ui.editors.base/src/org/jkiss/dbeaver/ui/editors/text/handlers/SaveTextFileHandler.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/plugin.xml
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/controls/ScriptSelectorPanel.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditor.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/handlers/SQLEditorHandlerOpenEditor.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/handlers/SQLEditorHandlerOpenObjectConsole.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/handlers/SQLEditorHandlerRenameFile.java
  plugins/org.jkiss.dbeaver.ui.navigator/plugin.xml
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/actions/GlobalPropertyTester.java
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/actions/ObjectPropertyTester.java
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/actions/datasource/DataSourceToolbarUtils.java
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/internal/UINavigatorMessages.java
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/internal/UINavigatorMessages.properties
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorUtils.java
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/actions/NavigatorHandlerObjectCreateCopy.java
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/actions/NavigatorHandlerObjectCreateNew.java
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/actions/NavigatorHandlerObjectRename.java
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/project/ProjectExplorerView.java
  plugins/org.jkiss.dbeaver.ui/icons/readonly_resources.png
  plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/DBeaverIcons.java
  plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/UIIcon.java
Labels: build:ee

#17728 #15319 default client changed for 8th for MySQL; 5 and 8 clients are …
  plugins/org.jkiss.dbeaver.ext.mysql/plugin.xml
Labels: build:ee

#17725 #16687 Fix json editing for mysql
  plugins/org.jkiss.dbeaver.ext.mysql/src/org/jkiss/dbeaver/ext/mysql/model/MySQLDialect.java
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/jdbc/data/JDBCContentChars.java
Labels: build:ee

#17561 dbeaver/dbeaver-ee#1771 add child types for sqlite
  plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/editor/ERDGraphicalViewer.java
  plugins/org.jkiss.dbeaver.ext.sqlite/src/org/jkiss/dbeaver/ext/sqlite/edit/SQLiteTableManager.java
Labels: build:ee
