Repository dbeaver/dbeaver, pull requests merged in 2022-04, with the labels that each got.

#16124 i18n_it add italian translations
  plugins/org.jkiss.dbeaver.core/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources_it.properties
  plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.data.transfer/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/internal/DTMessages_it.properties
  plugins/org.jkiss.dbeaver.erd.ui/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.ext.generic.ui/src/org/jkiss/dbeaver/ext/generic/internal/GenericResources_it.properties
  plugins/org.jkiss.dbeaver.ext.mysql.ui/src/org/jkiss/dbeaver/ext/mysql/ui/internal/MySQLUIMessages_it.properties
  plugins/org.jkiss.dbeaver.ext.postgresql.ui/src/org/jkiss/dbeaver/ext/postgresql/PostgresResources_it.properties
  plugins/org.jkiss.dbeaver.ext.sample.database/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.tasks.ui.view/src/org/jkiss/dbeaver/tasks/ui/internal/TaskUIViewMessages_it.properties
  plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/internal/CoreApplicationMessages_it.properties
  plugins/org.jkiss.dbeaver.ui.editors.connection/src/org/jkiss/dbeaver/ui/internal/UIConnectionMessages_it.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages_it.properties
  plugins/org.jkiss.dbeaver.ui.navigator/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/internal/UINavigatorMessages_it.properties
  plugins/org.jkiss.dbeaver.ui.search/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.ui.search/src/org/jkiss/dbeaver/ui/search/internal/UISearchMessages_it.properties
  plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/internal/UIMessages_it.properties
Labels: xf:i18n, sp:2

#16182 Fix typo for importing connections from sqldeveloper
  plugins/org.jkiss.dbeaver.ext.oracle.ui/src/org/jkiss/dbeaver/ext/oracle/ui/tools/sqldeveloper/ConfigImportWizardPageSqlDeveloper.java
Labels: bug

#16232 #15950 Fix the behavior of toggling line comment
  plugins/org.jkiss.dbeaver.ui.editors.base/src/org/jkiss/dbeaver/ui/editors/text/handlers/ToggleSingleLineCommentHandler.java
Labels: enhancement
