Repository dbeaver/dbeaver, pull requests merged in 2022-02, with the labels that each got.

#15331 Speedup Oracle metadata load
  plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/model/OracleSchema.java
Labels: enhancement, x:oracle, xf:metadata

#15473 Update Japanese translations
  plugins/org.jkiss.dbeaver.ext.exasol/OSGI-INF/l10n/bundle_ja.properties
  plugins/org.jkiss.dbeaver.ext.generic/OSGI-INF/l10n/bundle_ja.properties
  plugins/org.jkiss.dbeaver.ext.mysql/OSGI-INF/l10n/bundle_ja.properties
  plugins/org.jkiss.dbeaver.ext.oracle/OSGI-INF/l10n/bundle_ja.properties
Labels: sp:1

#15560 Added some new italian localizations
  plugins/org.jkiss.dbeaver.core/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources_it.properties
  plugins/org.jkiss.dbeaver.ext.postgresql.ui/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.ext.ui.tipoftheday/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.model/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.registry/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.ui.app.eclipse/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.ui.editors.connection/src/org/jkiss/dbeaver/ui/internal/UIConnectionMessages_it.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/internal/ResultSetMessages_it.properties
  plugins/org.jkiss.dbeaver.ui.navigator/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/internal/UINavigatorMessages_it.properties
  plugins/org.jkiss.dbeaver.ui.search/src/org/jkiss/dbeaver/ui/search/internal/UISearchMessages_it.properties
  plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/internal/UIMessages_it.properties
Labels: xf:i18n, sp:2
