Repository dbeaver/dbeaver, pull requests merged in 2022-05, with the labels that each got.

#16459 #16029 Add new tips
  plugins/org.jkiss.dbeaver.ext.ui.tipoftheday/build.properties
  plugins/org.jkiss.dbeaver.ext.ui.tipoftheday/nl/ru/tips.xml
  plugins/org.jkiss.dbeaver.ext.ui.tipoftheday/src/org/jkiss/dbeaver/ext/ui/tipoftheday/ShowTipOfTheDayDialog.java
  plugins/org.jkiss.dbeaver.ext.ui.tipoftheday/tips.xml
  plugins/org.jkiss.dbeaver.ui.app.standalone/plugin.xml
Labels: build:ee

#16465 #15437 Completed some Simplified Chinese localization work
  plugins/org.jkiss.dbeaver.core/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources_zh.properties
  plugins/org.jkiss.dbeaver.erd.ui/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ext.mysql.ui/src/org/jkiss/dbeaver/ext/mysql/ui/internal/MySQLUIMessages_zh.properties
  plugins/org.jkiss.dbeaver.ext.oracle.ui/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ext.oracle.ui/src/org/jkiss/dbeaver/ext/oracle/ui/internal/OracleUIMessages_zh.properties
  plugins/org.jkiss.dbeaver.ext.oracle/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ext.postgresql.ui/src/org/jkiss/dbeaver/ext/postgresql/PostgresResources_zh.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.registry/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.app.eclipse/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.base/src/org/jkiss/dbeaver/ui/editors/internal/EditorsResources_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.connection/src/org/jkiss/dbeaver/ui/internal/UIConnectionMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/internal/ResultSetMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/editors/data/internal/DataEditorsResources_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.session/src/org/jkiss/dbeaver/ui/views/session/internal/SessionEditorMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/internal/UINavigatorMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/internal/UIMessages_zh.properties
Labels: xf:i18n, sp:1

#16488 dbeaver/dbeaver-ee#1262 fix column arrangement for document db's
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetModel.java
Labels: build:ee

#16495 Italian translations for SQL server
  plugins/org.jkiss.dbeaver.ext.mssql/OSGI-INF/l10n/bundle_it.properties
Labels: xf:i18n, sp:1

#16511 Added missing italian translations for dbeaver.model
  plugins/org.jkiss.dbeaver.model/OSGI-INF/l10n/bundle_it.properties
Labels: xf:i18n, sp:1

#16497 dbeaver/dbeaver-ee#1400 Fix object detection for context menu resolution in erd for mongo
  plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/model/ERDObjectAdapter.java
Labels: build:ee

#16507 dbeaver/dbeaver-ee#1589 Keep temporary files after DND is finished
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorUtils.java
Labels: build:ue

#16534 #16451 fix buttons in custom erd diagrams
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/e4/DBeaverStackRenderer.java
Labels: build:ee

#16549 Update bundle_es.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_es.properties
Labels: xf:i18n

#16577 dbeaver/dbeaver-ee#1495 fix document transformers
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/virtual/DBVUtils.java
Labels: build:ee

#16599 dbeaver/dbeaver-ee#1496 Support raw collection types
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/data/dialogs/ComplexObjectEditor.java
Labels: build:ee

#16460 EpochTimeAttributeTransformer.java: add 4 more modes
  plugins/org.jkiss.dbeaver.model/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.model/plugin.xml
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/data/transformers/EpochTimeAttributeTransformer.java
Labels: enhancement

#16615 dbeaver/dbeaver-ee#1655 DROP TABLE to dangerous query execution confirmation
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/preferences/PrefPageConfirmations.java
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/sql/SQLQuery.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditor.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLPreferenceConstants.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages.properties
Labels: build:ee

#16633 dbeaver/dbeaver-ee#1493 target DDL message changed for no sql databases
  plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/internal/DTUIMessages.java
  plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/internal/DTUIMessages.properties
  plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/internal/DTUIMessages_ru.properties
  plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/pages/database/DatabaseConsumerPageMapping.java
Labels: build:ee
