Repository dbeaver/dbeaver, pull requests merged in 2022-10, with the labels that each got.

#17771 #17139 streams, tasks, stages and pipes support added for Snowflake
  plugins/org.jkiss.dbeaver.ext.snowflake.core/src/org/jkiss/dbeaver/ext/snowflake/SnowflakeConstants.java
  plugins/org.jkiss.dbeaver.ext.snowflake.core/src/org/jkiss/dbeaver/ext/snowflake/model/SnowflakeSQLDialect.java
Labels: build:ee

#17741 dbeaver/dbeaver-ee#1956 HSQL plain execution plan
  plugins/org.jkiss.dbeaver.ext.hsqldb/src/org/jkiss/dbeaver/ext/hsqldb/model/HSQLMetaModel.java
  plugins/org.jkiss.dbeaver.ext.hsqldb/src/org/jkiss/dbeaver/ext/hsqldb/model/plan/HSQLExecutionPlan.java
  plugins/org.jkiss.dbeaver.ext.hsqldb/src/org/jkiss/dbeaver/ext/hsqldb/model/plan/HSQLQueryPlanner.java
Labels: build:ee

#17735 #17591 Add preference for Windows to use or not Windows trust store
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreMessages.java
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources.properties
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/preferences/PrefPageConnectionsGeneral.java
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/ModelPreferences.java
  plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/DBeaverApplication.java
  product/appstore/DBeaverAppStore.product
  product/community/DBeaver.product
Labels: build:ee

#17884 dbeaver/dbeaver-ee#2044 fix(security): update pgjdbc due to known CVEs
  plugins/org.jkiss.dbeaver.ext.generic/plugin.xml
  plugins/org.jkiss.dbeaver.ext.greenplum/plugin.xml
  plugins/org.jkiss.dbeaver.ext.postgresql/plugin.xml
Labels: build:le

#17923 #17649 Hide network-related configuration pages for embedded drivers
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/dialogs/connection/ConnectionPageSettings.java
Labels: build:ee

#17936 #16205 Append data to existing sheets
  plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.data.office/plugin.xml
  plugins/org.jkiss.dbeaver.data.office/src/org/jkiss/dbeaver/data/office/export/DataExporterXLSX.java
Labels: build:ee

#17912 dbeaver/dbeaver-ee#1995 File conflict behavior in data export
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/DesktopUI.java
  plugins/org.jkiss.dbeaver.data.transfer.ui/META-INF/MANIFEST.MF
  plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/pages/stream/StreamConsumerPageOutput.java
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/IDataTransferConsumer.java
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/IDataTransferSettings.java
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/internal/DTMessages.java
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/internal/DTMessages.properties
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/StreamConsumerSettings.java
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/stream/StreamTransferConsumer.java
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/task/DTTaskHandlerTransfer.java
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/runtime/ui/DBPPlatformUI.java
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/runtime/ui/console/ConsoleUserInterface.java
  plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/dialogs/MessageBoxBuilder.java
  plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/dialogs/MessageBoxModern.java
Labels: build:ee

#17896 #16440 Include description column when exporting as XLSX
  plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_de.properties
  plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_ja.properties
  plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_ko.properties
  plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_ru.properties
  plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.data.office/plugin.xml
  plugins/org.jkiss.dbeaver.data.office/src/org/jkiss/dbeaver/data/office/export/DataExporterXLSX.java
Labels: build:ee

#17966 dbeaver/dbeaver-ee#1725 remove queries from the log
  plugins/org.jkiss.dbeaver.core/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.core/plugin.xml
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/messages/ModelMessages.java
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/messages/ModelResources.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/controls/querylog/QueryLogCommandHandler.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/controls/querylog/QueryLogViewer.java
Labels: build:ee

#18009 dbeaver/dbeaver-ee#2088 confirmation if statement opens a lot of results
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLPreferenceConstants.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/execute/SQLQueryJob.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorPreferencesInitializer.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/preferences/PrefPageSQLEditor.java
Labels: build:ee

#17960 dbeaver/dbeaver-ee#2043 NIO filesystem directory creation/deletion
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/fs/nio/NIOFolder.java
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNResource.java
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/NavigatorAdapterFactory.java
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/actions/NavigatorHandlerCreateFolder.java
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/actions/NavigatorHandlerObjectCreateNew.java
Labels: build:ue
