Repository dbeaver/dbeaver, pull requests merged in 2023-10, with the labels that each got.

#21330 #19866 Find node with missing nodes in-between
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNModel.java
Labels: check:cloudbeaver

#21186 Add support driver for Dameng
  features/org.jkiss.dbeaver.db.feature/feature.xml
  features/org.jkiss.dbeaver.db.ui.feature/feature.xml
  plugins/org.jkiss.dbeaver.ext.dameng.ui/META-INF/MANIFEST.MF
  plugins/org.jkiss.dbeaver.ext.dameng.ui/build.properties
  plugins/org.jkiss.dbeaver.ext.dameng.ui/plugin.xml
  plugins/org.jkiss.dbeaver.ext.dameng.ui/pom.xml
  plugins/org.jkiss.dbeaver.ext.dameng.ui/src/org/jkiss/dbeaver/ext/dameng/ui/config/DamengSchemaConfigurator.java
  plugins/org.jkiss.dbeaver.ext.dameng.ui/src/org/jkiss/dbeaver/ext/dameng/ui/config/DamengSequenceConfigurator.java
  plugins/org.jkiss.dbeaver.ext.dameng/META-INF/MANIFEST.MF
  plugins/org.jkiss.dbeaver.ext.dameng/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.ext.dameng/build.properties
  plugins/org.jkiss.dbeaver.ext.dameng/icons/dm_icon.png
  plugins/org.jkiss.dbeaver.ext.dameng/icons/dm_icon@2x.png
  plugins/org.jkiss.dbeaver.ext.dameng/icons/dm_icon_big.png
  plugins/org.jkiss.dbeaver.ext.dameng/icons/dm_icon_big@2x.png
  plugins/org.jkiss.dbeaver.ext.dameng/plugin.xml
  plugins/org.jkiss.dbeaver.ext.dameng/pom.xml
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/DamengConstants.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/DamengDataSourceProvider.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/edit/DamengSchemaManager.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/edit/DamengSequenceManager.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/edit/DamengTableColumnManager.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/edit/DamengTableManager.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengDataSource.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengDataType.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengDataTypeCache.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengMetaModel.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengSQLDialect.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengSchema.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengTable.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengTableColumn.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengUtils.java
  plugins/pom.xml
Labels: external

#21365 dbeaver/dbeaver#21362 added Firebird Keywords.
  plugins/org.jkiss.dbeaver.ext.firebird/src/org/jkiss/dbeaver/ext/firebird/model/FireBirdSQLDialect.java
Labels: external

#21498 Fixing mistakes in the translation in the bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.data.transfer/OSGI-INF/l10n/bundle_pt_BR.properties
Labels: xf:i18n, external

#21381 #18312 Complete some Simplified Chinese localization work
  plugins/org.jkiss.dbeaver.core/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources_zh.properties
  plugins/org.jkiss.dbeaver.data.gis.view/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.data.gis.view/src/org/jkiss/dbeaver/ui/gis/internal/GISResources_zh.properties
  plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/internal/DTUIMessages_zh.properties
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/internal/DTMessages_zh.properties
  plugins/org.jkiss.dbeaver.erd.ui/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.erd.ui/src/org/jkiss/dbeaver/erd/ui/internal/ERDUIMessages_zh.properties
  plugins/org.jkiss.dbeaver.ext.db2/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ext.mssql/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ext.postgresql.ui/src/org/jkiss/dbeaver/ext/postgresql/PostgresResources_zh.properties
  plugins/org.jkiss.dbeaver.tasks.native.ui/src/org/jkiss/dbeaver/tasks/ui/nativetool/internal/TaskNativeUIMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql.terminal/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/internal/UIMessages_zh.properties
Labels: external

#21569 dbeaver/pro#1949 Disable install update operation
  plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/handlers/DataExportHandler.java
  plugins/org.jkiss.dbeaver.data.transfer/META-INF/MANIFEST.MF
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/runtime/policy/BasePolicyDataProvider.java
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/runtime/policy/PolicyDataProvider.java
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/DTConstants.java
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/task/DTTaskHandlerExport.java
  plugins/org.jkiss.dbeaver.registry/META-INF/MANIFEST.MF
  plugins/org.jkiss.dbeaver.registry/src/org/jkiss/dbeaver/registry/BasePolicyDataProvider.java
  plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/ApplicationActionBarAdvisor.java
  plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/services/ApplicationPolicyService.java
  plugins/org.jkiss.dbeaver.ui.editors.data/META-INF/MANIFEST.MF
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetViewer.java
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/handler/ResultSetHandlerMain.java
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/handler/ResultSetHandlerOpenWith.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/handlers/SQLEditorHandlerExportData.java
Labels: feature request

#21461 dbeaver#20446 added UUID Postgre keyword
  plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreDialect.java
Labels: external

#21642 Remove outdated docs/build.txt
  docs/build.txt
Labels: external

#21468 #21442 #21443 Fix create schema with the existing schema's name.
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/edit/DamengSchemaManager.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengDataSource.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengExecutionContext.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengMetaModel.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengSchema.java
Labels: external
