Repository dbeaver/dbeaver, pull requests merged in 2023-12, with the labels that each got.

#22088 dbeaver/pro#2204 code cleanup
  plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreEventTrigger.java
Labels: check:cloudbeaver

#21884 Define maxZoom as maxNativeZoom
  plugins/org.jkiss.dbeaver.data.gis.view/plugin.xml
Labels: xf:gis, external

#21979 #21944 Fix Oracle timestamp display error
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/sql/task/SQLScriptDataReceiver.java
  plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/data/OracleTemporalAccessorValueHandler.java
  plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/data/OracleTimestampConverter.java
  plugins/org.jkiss.dbeaver.ext.oracle/src/org/jkiss/dbeaver/ext/oracle/data/OracleTimestampValueHandler.java
Labels: external

#22023 fix: #10232 Improved italian translations
  plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/OSGI-INF/l10n/bundle_it.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/internal/ResultSetMessages_it.properties
  plugins/org.jkiss.dbeaver.ui.navigator/OSGI-INF/l10n/bundle_it.properties
Labels: xf:i18n, external
