Repository dbeaver/dbeaver, pull requests merged in 2023-04, with the labels that each got.

#19566 dbeaver/pro#1522 Do not encrypt values in secret storage (standalone)
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/app/LocalSecretController.java
Labels: build:ee

#19574 l10n(zh_TW): Update translations of bundle_tw.properties
  plugins/org.jkiss.dbeaver.cmp.simple.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.cmp.simple/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.core/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources_tw.properties
  plugins/org.jkiss.dbeaver.data.gis.view/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.data.gis/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.data.office.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.data.office/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.data.transfer.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.data.transfer/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.debug.core/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.debug.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.erd.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.db2.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.db2/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.exasol.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.exasol/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.firebird/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.generic.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.generic/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.greenplum/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.hana/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.hsqldb/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.mssql.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.mssql/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.mysql.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.mysql/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.oracle.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.oracle/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.postgresql.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.sample.database/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.sqlite/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.vertica/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.wmi/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.model.sql/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.model/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.net.ssh/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.registry/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.team.git.ui/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ui.app.eclipse/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ui.dashboard/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ui.editors.connection/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ui.editors.hex/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ui.navigator/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ui.search/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ui/OSGI-INF/l10n/bundle_tw.properties
Labels: sp:1, external

#19068 19043: Microseconds epoch transformer
  plugins/org.jkiss.dbeaver.model/plugin.xml
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/impl/data/transformers/EpochTimeAttributeTransformer.java
Labels: external

#19577 dbeaver_l10n_pt-BR
  plugins/org.jkiss.dbeaver.cmp.simple.ui/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.core/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources_pt_BR.properties
  plugins/org.jkiss.dbeaver.data.gis.view/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.data.gis/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.debug.ui/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ext.generic.ui/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ext.postgresql.ui/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ext.postgresql.ui/src/org/jkiss/dbeaver/ext/postgresql/PostgresResources_pt_BR.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ext.spanner.ui/src/org/jkiss/dbeaver/ext/spanner/ui/internal/messages_pt_BR.properties
  plugins/org.jkiss.dbeaver.ext.ui.tipoftheday/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.model/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/messages/ModelResources_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.app.eclipse/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.dashboard/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.dashboard/src/org/jkiss/dbeaver/ui/dashboard/internal/UIDashboardMessages_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.editors.connection/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.editors.connection/src/org/jkiss/dbeaver/ui/internal/UIConnectionMessages_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.editors.session/src/org/jkiss/dbeaver/ui/views/session/internal/SessionEditorMessages_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql.terminal/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql.terminal/src/org/jkiss/dbeaver/ui/editors/sql/terminal/SQLTerminalMessages_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.navigator/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/internal/UINavigatorMessages_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.search/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui.search/src/org/jkiss/dbeaver/ui/search/internal/UISearchMessages_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/internal/UIMessages_pt_BR.properties
Labels: sp:1, external

#19669 dbeaver/pro#1514 disable attribute preservation
  plugins/org.jkiss.dbeaver.net.ssh.sshj/src/org/jkiss/dbeaver/model/net/ssh/SSHImplementationSshj.java
Labels: build:ee

#19745 Fix Typo: Support TiDB Cloud Telemetry
  plugins/org.jkiss.dbeaver.ext.tidb/src/org/jkiss/dbeaver/ext/tidb/mysql/model/TiDBMySQLDataSource.java
Labels: external
