Repository dbeaver/dbeaver, pull requests merged in 2023-07, with the labels that each got.

#20240 Update Google BigQuery JDBC driver to version 1.3.3
  plugins/org.jkiss.dbeaver.ext.bigquery/plugin.xml
Labels: external

#20458 Fixed DE translation für 'Insertion case'
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages_de.properties
Labels: xf:i18n, external

#20553 Materialize driver
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_de.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_ru.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/icons/materialize_icon.png
  plugins/org.jkiss.dbeaver.ext.postgresql/icons/materialize_icon@2x.png
  plugins/org.jkiss.dbeaver.ext.postgresql/icons/materialize_icon_big.png
  plugins/org.jkiss.dbeaver.ext.postgresql/icons/materialize_logo.png
  plugins/org.jkiss.dbeaver.ext.postgresql/plugin.xml
  plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/impls/materialize/PostgreServerMaterialize.java
Labels: new driver, external

#20549 Add CrateDB variant of PostgreServer to improve compatibility
  plugins/org.jkiss.dbeaver.ext.generic/icons/cratedb_icon.png
  plugins/org.jkiss.dbeaver.ext.generic/icons/cratedb_icon@2x.png
  plugins/org.jkiss.dbeaver.ext.generic/icons/cratedb_icon_big.png
  plugins/org.jkiss.dbeaver.ext.generic/icons/cratedb_icon_big@2x.png
  plugins/org.jkiss.dbeaver.ext.generic/plugin.xml
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_de.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_pt_BR.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_ru.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_tw.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ext.postgresql/icons/cratedb_logo.png
  plugins/org.jkiss.dbeaver.ext.postgresql/plugin.xml
  plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/impls/PostgreServerCrateDB.java
Labels: new driver, external

#20470 dbeaver#18312 Complete some Simplified Chinese localization work
  plugins/org.jkiss.dbeaver.core/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.data.transfer.ui/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.data.transfer.ui/src/org/jkiss/dbeaver/tools/transfer/ui/internal/DTUIMessages_zh.properties
  plugins/org.jkiss.dbeaver.data.transfer/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.data.transfer/src/org/jkiss/dbeaver/tools/transfer/internal/DTMessages_zh.properties
  plugins/org.jkiss.dbeaver.ext.sample.database/src/org/jkiss/dbeaver/ext/sample/database/SampleDatabaseResources_zh.properties
  plugins/org.jkiss.dbeaver.tasks.ui/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/internal/CoreApplicationMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/internal/ResultSetMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/editors/data/internal/DataEditorsResources_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql.terminal/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/OSGI-INF/l10n/bundle_zh.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/internal/SQLEditorMessages_zh.properties
  plugins/org.jkiss.dbeaver.ui.navigator/OSGI-INF/l10n/bundle_zh.properties
Labels: xf:i18n, external

#20315 Update timescale branding
  plugins/org.jkiss.dbeaver.ext.postgresql/icons/timescale_icon.png
  plugins/org.jkiss.dbeaver.ext.postgresql/icons/timescale_icon@2x.png
  plugins/org.jkiss.dbeaver.ext.postgresql/icons/timescale_icon_big.png
  plugins/org.jkiss.dbeaver.ext.postgresql/icons/timescale_icon_big@2x.png
  plugins/org.jkiss.dbeaver.ext.postgresql/icons/timescale_logo.png
Labels: external

#20625 dbeaver/#20624 added Redshift Keywords.
  plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/impls/redshift/PostgreServerRedshift.java
Labels: external
