Repository dbeaver/dbeaver, pull requests merged in 2023-02, with the labels that each got.

#18977 dbeaver/pro#1393 Fix secured project refresh
  plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/navigator/DBNProject.java
  plugins/org.jkiss.dbeaver.ui.navigator/src/org/jkiss/dbeaver/ui/navigator/actions/NavigatorHandlerRefresh.java
Labels: build:ee

#18916 Updated InterSystems IRIS JDBC driver location
  plugins/org.jkiss.dbeaver.ext.generic/plugin.xml
Labels: external

#18945 18944 Change defaults for Exasol connections parameters.
  plugins/org.jkiss.dbeaver.ext.exasol/plugin.xml
  plugins/org.jkiss.dbeaver.ext.exasol/src/org/jkiss/dbeaver/ext/exasol/ExasolConstants.java
  plugins/org.jkiss.dbeaver.ext.exasol/src/org/jkiss/dbeaver/ext/exasol/ExasolDataSourceProvider.java
  plugins/org.jkiss.dbeaver.ext.exasol/src/org/jkiss/dbeaver/ext/exasol/model/ExasolDataSource.java
Labels: external

#18987 #18747 update SQL Server, Babelfish and Azure drivers to version 11.2.3
  plugins/org.jkiss.dbeaver.ext.mssql.ui/src/org/jkiss/dbeaver/ext/mssql/ui/SQLServerConnectionPage.java
  plugins/org.jkiss.dbeaver.ext.mssql.ui/src/org/jkiss/dbeaver/ext/mssql/ui/views/SQLServerSSLConfigurator.java
  plugins/org.jkiss.dbeaver.ext.mssql/plugin.xml
  plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/SQLServerConstants.java
  plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/model/SQLServerDataSource.java
Labels: build:ee

#18421 import using directly the url
  plugins/org.jkiss.dbeaver.ext.import_config/src/org/jkiss/dbeaver/ext/import_config/wizards/ConfigImportWizard.java
  plugins/org.jkiss.dbeaver.ext.import_config/src/org/jkiss/dbeaver/ext/import_config/wizards/ImportConnectionInfo.java
  plugins/org.jkiss.dbeaver.ext.import_config/src/org/jkiss/dbeaver/ext/import_config/wizards/custom/ConfigImportWizardPageCustomConnections.java
Labels: sp:1, external

#19139 fix(properties): typo in French core properties
  plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/core/CoreResources_fr.properties
Labels: external

#19164 dbeaver/pro#1442 Kerberos auth model config change. Legacy driver rem…
  plugins/org.jkiss.dbeaver.ext.mssql/plugin.xml
  plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/auth/SQLServerAuthModelKerberos.java
Labels: build:ee

#19059 #19046 Support user-defined keybinding for pinning/unpinning active results tab
  plugins/org.jkiss.dbeaver.ui.editors.sql/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.ui.editors.sql/plugin.xml
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditor.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/SQLEditorCommands.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/handlers/SQLEditorHandlerToggleTabPinned.java
Labels: external
