Repository dbeaver/dbeaver, pull requests merged in 2024-01, with the labels that each got.

#21872 Show copy only for DBPNamedObject
  plugins/org.jkiss.dbeaver.ui.navigator/plugin.xml
Labels: external

#22363 #22328 Fix Procedures are hidden in navigator if any function exist in a schema
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengMetaModel.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengSQLDialect.java
Labels: external, x:dameng

#22362 update dameng driver version,add categories
  plugins/org.jkiss.dbeaver.ext.dameng/plugin.xml
Labels: external, x:dameng

#22278 dbeaver/pro#2145 disable encrypt if ssl is not active
  plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/model/SQLServerDataSource.java
Labels: check:cloudbeaver

#22391 Added support for Dameng user and role
  plugins/org.jkiss.dbeaver.ext.dameng.ui/plugin.xml
  plugins/org.jkiss.dbeaver.ext.dameng/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.ext.dameng/plugin.xml
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/DamengConstants.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengDataFile.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengDataSource.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengMetaModel.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengPrivObject.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengPrivSystem.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengPrivUser.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengRole.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengTablespace.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengUser.java
  plugins/org.jkiss.dbeaver.ext.dameng/src/org/jkiss/dbeaver/ext/dameng/model/DamengUtils.java
Labels: external, x:dameng

#22298 Fix: SQL Server: Source tab is empty in the index properties #13529
  plugins/org.jkiss.dbeaver.ext.mssql/src/org/jkiss/dbeaver/ext/mssql/model/SQLServerTableIndex.java
Labels: external

#22480 Corrected Translation of 'QuoteChar' in Japanese Localization
  plugins/org.jkiss.dbeaver.data.transfer/OSGI-INF/l10n/bundle_ja.properties
Labels: xf:i18n, external

#22536 Added ScyllaDB to the list of supported datasources
  README.md
Labels: external

#22513 dbeaver/dbeaver#22305 Added Functions support for Snowflake SQL Editor
  plugins/org.jkiss.dbeaver.ext.snowflake.core/src/org/jkiss/dbeaver/ext/snowflake/model/SnowflakeSQLDialect.java
Labels: external

#22106 dbeaver/dbeaver#21832 Add Cubrid Plugin Features
  features/org.jkiss.dbeaver.db.feature/feature.xml
  plugins/org.jkiss.dbeaver.ext.cubrid/META-INF/MANIFEST.MF
  plugins/org.jkiss.dbeaver.ext.cubrid/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.ext.cubrid/build.properties
  plugins/org.jkiss.dbeaver.ext.cubrid/icons/cubrid_icon.png
  plugins/org.jkiss.dbeaver.ext.cubrid/icons/cubrid_icon@2x.png
  plugins/org.jkiss.dbeaver.ext.cubrid/icons/cubrid_icon_big.png
  plugins/org.jkiss.dbeaver.ext.cubrid/icons/cubrid_icon_big@2x.png
  plugins/org.jkiss.dbeaver.ext.cubrid/plugin.xml
  plugins/org.jkiss.dbeaver.ext.cubrid/pom.xml
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/CubridConstants.java
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/CubridDataSourceProvider.java
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/CubridDataSource.java
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/CubridObjectContainer.java
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/CubridSQLDialect.java
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/CubridTable.java
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/CubridUser.java
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/CubridView.java
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/meta/CubridMetaModel.java
  plugins/pom.xml
Labels: external
