Repository dbeaver/dbeaver, pull requests merged in 2024-04, with the labels that each got.

#22829 feat: automatic row count
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetPreferences.java
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/ResultSetViewer.java
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/internal/ResultSetMessages.java
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/controls/resultset/internal/ResultSetMessages.properties
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/editors/data/internal/DataEditorsPreferencesInitializer.java
  plugins/org.jkiss.dbeaver.ui.editors.data/src/org/jkiss/dbeaver/ui/editors/data/preferences/PrefPageResultSetMain.java
Labels: external

#23329 Update French translations
  plugins/org.jkiss.dbeaver.ext.postgresql/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.ext.ui.tipoftheday/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.model.jdbc/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.model.sm/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.model.sql/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.model/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.registry/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.tasks.ui.view/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.tasks.ui/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.team.git.ui/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.ui.app.eclipse/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.ui.app.standalone/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.ui.charts/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.ui.navigator/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.ui.search/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.ui.statistics/OSGI-INF/l10n/bundle_fr.properties
  plugins/org.jkiss.dbeaver.ui/OSGI-INF/l10n/bundle_fr.properties
Labels: xf:i18n, external

#29265 dbeaver/pro#2794 Fix acquisition of the active display
  plugins/org.jkiss.dbeaver.ui/src/org/jkiss/dbeaver/ui/ProgramInfo.java
Labels: pkg:UE
