Repository dbeaver/dbeaver, pull requests merged in 2025-07, with the labels that each got.

#38370 #37720 [CUBRID] Fix objects can't be opened from SQL Editor with hyperlinks
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/CubridConstants.java
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/CubridDataSource.java
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/CubridStructureAssistant.java
Labels: external

#38648 `README.md`: Remove Duplicate Item
  README.md
Labels: external

#38693 fix arrow_top
  plugins/org.jkiss.dbeaver.ui/icons/misc/arrow_top.svg
Labels: external

#35941 [CUBRID] Add Tab for Display FullText of Query Plan
  plugins/org.jkiss.dbeaver.ext.cubrid.ui/OSGI-INF/l10n/bundle.properties
  plugins/org.jkiss.dbeaver.ext.cubrid.ui/build.properties
  plugins/org.jkiss.dbeaver.ext.cubrid.ui/plugin.xml
  plugins/org.jkiss.dbeaver.ext.cubrid.ui/src/org/jkiss/dbeaver/ext/cubrid/ui/editors/CubridSQLPlanViewProvider.java
  plugins/org.jkiss.dbeaver.ext.cubrid/META-INF/MANIFEST.MF
  plugins/org.jkiss.dbeaver.ext.cubrid/src/org/jkiss/dbeaver/ext/cubrid/model/plan/CubridPlanAnalyser.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/plan/ExplainPlanViewer.java
  plugins/org.jkiss.dbeaver.ui.editors.sql/src/org/jkiss/dbeaver/ui/editors/sql/plan/registry/SQLPlanViewDescriptor.java
Labels: external

#38781 Potential fix for code scanning alert no. 78: Resolving XML external entity in user-controlled data
  plugins/org.jkiss.dbeaver.ui.app.standalone/src/org/jkiss/dbeaver/ui/app/standalone/tipoftheday/ShowTipOfTheDayHandler.java
Labels: security

#38795 Fix zh translation error
  plugins/org.jkiss.dbeaver.ext.oracle/OSGI-INF/l10n/bundle_zh.properties
Labels: xf:i18n, external
